### ISSUE TITLE
嘗試在Windows環境下部屬Naifu

### ISSUE THREAD

**Issue by H3XDaemon** [JingShing/novelai-colab-ver#11]
Starting Hydra Node HTTP TOKEN=None
2022-10-14 22:18:02,181 INFO config.py(4152) - CPU: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
2022-10-14 22:18:02,181 INFO config.py(4152) - GPU: NVIDIA GeForce RTX 3060
2022-10-14 22:18:02,181 INFO config.py(4152) - GPU RAM: 12gb
2022-10-14 22:18:02,181 INFO config.py(4152) - MODEL: stable-diffusion
2022-10-14 22:18:02,181 INFO models.py(4152) - Loading model from file models/animefull-final-pruned.ckpt
Traceback (most recent call last):
  File "C:\Users\User\Documents\AI\Novel\naifu\naifu\.\hydra_node\config.py", line 157, in init_config_model
    model = no_init(lambda: model_map[config.model_name](config))
  File "C:\Users\User\Documents\AI\Novel\naifu\naifu\.\hydra_node\config.py", line 34, in no_init
    result = loading_code()
  File "C:\Users\User\Documents\AI\Novel\naifu\naifu\.\hydra_node\config.py", line 157, in <lambda>
    model = no_init(lambda: model_map[config.model_name](config))
  File "C:\Users\User\Documents\AI\Novel\naifu\naifu\.\hydra_node\models.py", line 204, in __init__
    model, model_config = self.from_file(config.model_path)
  File "C:\Users\User\Documents\AI\Novel\naifu\naifu\venv\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'StableDiffusionModel' object has no attribute 'from_file'
2022-10-14 22:18:02,182 ERROR config.py(4152) - Failed to load model: 'StableDiffusionModel' object has no attribute 'from_file'
請按任意鍵繼續 . . .

**Comment by JingShing** [comment]
請試試 [這個版本](https://github.com/JingShing/NovelAI-4chan-lowvram-ver)

**Comment by H3XDaemon** [comment]
謝謝:D
